"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useConvexAuth, useMutation, useQuery } from "convex/react";
import { ConvexError } from "convex/values";
import type { FunctionReturnType } from "convex/server";
import { api } from "@/convex/_generated/api";
import { useAuth } from "@/components/auth-context";
import { QueryBoundary } from "@/components/catalog/query-boundary";
import { authIsConfigured } from "@/lib/auth-client";
import { StatePanel } from "@/components/catalog/catalog-states";
import { Button, buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cardVariants } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { alertText, fieldHint, fieldLabel, heading2, heading3, heading4, label, lead, muted, nativeCheckbox, nativeSelect, statusText, tagline } from "@/lib/typography";

const button = buttonVariants();
const card = `${cardVariants()} min-w-0 p-6 sm:p-8`;
type Catalog = FunctionReturnType<typeof api.academy.catalog>;
type Mine = FunctionReturnType<typeof api.academy.mine>;
function message(error: unknown) { return error instanceof ConvexError && typeof error.data === "string" ? error.data : "We couldn’t save that change. Please try again."; }
function safeUrl(value?: string) { try { return value && new URL(value).protocol === "https:" ? value : null; } catch { return null; } }
function price(cents?: number) { return cents === undefined ? "Quote Required" : cents === 0 ? "Free" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100); }
function ServiceForm({ service, close }: { service: Catalog["services"][number]; close: () => void }) {
  const { user } = useAuth(); const request = useMutation(api.academy.request);
  const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); setError("");
    try { await request({ serviceId: service._id, name: String(data.get("name")), projectTitle: String(data.get("title")), genre: String(data.get("genre")), wordCount: Number(data.get("words")), timeline: String(data.get("timeline")), notes: String(data.get("goals")), sample: String(data.get("sample")), consent: data.get("consent") === "on" }); close(); }
    catch (err) { setError(message(err)); } finally { setBusy(false); }
  }
  return <form className="mt-6 grid gap-5 border-t border-hairline pt-6" onSubmit={submit}>
    <h3 className={heading4}>Your Project Brief</h3><p className={muted}>This is a request, not a confirmed appointment. No payment is collected. Availability, scope, and any fee must be agreed before work begins.</p>
    <label className={fieldLabel}>Name<Input name="name" defaultValue={user?.name} autoComplete="name" required minLength={2} maxLength={100} /></label>
    <p className={`break-all ${muted}`}>Account Email: {user?.email}</p>
    <label className={fieldLabel}>Project Title<Input name="title" required minLength={2} maxLength={200} /></label>
    <div className="grid gap-4 sm:grid-cols-2"><label className={fieldLabel}>Genre<Input name="genre" required minLength={2} maxLength={100} /></label><label className={fieldLabel}>Manuscript Word Count<Input name="words" type="number" required min={1} max={1000000} step={1} /></label></div>
    <label className={fieldLabel}>Preferred Timeline<Input name="timeline" placeholder="For example: flexible, or hoping for October" required minLength={2} maxLength={300} /></label>
    <label className={fieldLabel}>What Would You Like Help With?<Textarea name="goals" rows={4} required minLength={20} maxLength={5000} /></label>
    <label className={fieldLabel}>Manuscript Sample {service.slug === "first-ten-pages-review" ? "(Required)" : "(Optional)"}<Textarea name="sample" rows={7} required={service.slug === "first-ten-pages-review"} minLength={service.slug === "first-ten-pages-review" ? 20 : undefined} maxLength={30000} /><span className={fieldHint}>Paste up to ten manuscript pages, maximum 3,000 words. Text only; no public document link is needed.</span></label>
    <label className="flex items-start gap-3 text-small text-body"><input name="consent" type="checkbox" required className={nativeCheckbox} /><span>I have permission to share this writing and authorize studio staff to review it and respond about this request. This does not subscribe me to marketing.</span></label>
    {error && <p role="alert" className={alertText}>{error}</p>}<div className="flex flex-wrap items-center gap-4"><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Send Request"}</Button><Button variant="link" size="link" type="button" disabled={busy} onClick={close}>Close</Button></div>
  </form>;
}
function ServiceCard({ service, mine, authenticated }: { service: Catalog["services"][number]; mine?: Mine; authenticated: boolean }) {
  const [open,setOpen] = useState(false);
  const active = mine?.requests.some(r => r.serviceId === service._id && (r.status === "requested" || r.status === "scheduled"));
  const bookingUrl = safeUrl(service.bookingUrl);
  return <article className={card}><div className="flex flex-wrap items-start justify-between gap-3"><h2 className={heading3}>{service.title}</h2><Badge>{price(service.priceInCents)}</Badge></div><p className="my-4 whitespace-pre-wrap text-body">{service.description}</p>{service.durationMinutes && <p className={`mb-3 ${label}`}>{service.durationMinutes} minutes</p>}{service.intakeInstructions && <p className={`mb-5 whitespace-pre-wrap ${muted}`}>{service.intakeInstructions}</p>}
    {active ? <a href="#studio-requests" className={button}>View Your Request</a> : bookingUrl ? <a href={bookingUrl} className={button} target="_blank" rel="noopener noreferrer">Open Booking Provider ↗</a> : service.bookingUrl ? <p className={statusText}>Booking is temporarily unavailable. Please contact the studio.</p> : !authenticated ? <Link className={button} href="/signin?next=/academy">Sign In to Request</Link> : !mine ? <p role="status" className={statusText}>Loading your requests…</p> : !open ? <Button onClick={() => setOpen(true)}>Request {service.priceInCents === 0 ? "a Free Review" : "This Service"}</Button> : <ServiceForm service={service} close={() => setOpen(false)} />}
  </article>;
}
function InterestButton({ courseId, active }: { courseId?: Catalog["courses"][number]["_id"]; active: boolean }) {
  const mutate = useMutation(api.academy.interest); const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  async function change() { setBusy(true); setError(""); try { await mutate({ courseId, active: !active }); } catch(err) { setError(message(err)); } finally { setBusy(false); } }
  return <div>{active && <p role="status" className="mb-3 font-ui text-small font-semibold text-champagne">Your Interest Is Saved</p>}<Button variant={active ? "secondary" : "default"} disabled={busy} onClick={() => void change()}>{busy ? "Saving…" : active ? "Remove My Interest" : "Save My Interest"}</Button>{error && <p role="alert" className={`mt-3 ${alertText}`}>{error}</p>}</div>;
}
function RequestCard({ request }: { request: Mine["requests"][number] }) {
  const cancel = useMutation(api.academy.cancelRequest); const [confirm,setConfirm] = useState(false); const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  async function withdraw() { setBusy(true); setError(""); try { await cancel({id:request._id}); setConfirm(false); } catch(err) { setError(message(err)); } finally { setBusy(false); } }
  return <article className={card}><div className="flex flex-wrap items-center gap-3"><h3 className={heading4}>{request.serviceTitle}</h3><Badge variant="outline">{request.status}</Badge></div><p className="my-2 break-words text-body">{request.projectTitle ?? "Your Project"}</p><p className={muted}>Submitted {new Date(request.createdAt).toISOString().slice(0,10)}</p>{request.scheduledAt && <p className="text-cream">Appointment: {new Date(request.scheduledAt).toISOString().replace("T"," ").slice(0,16)} UTC</p>}{request.staffReply && <div className="my-4 rounded-form border-l-2 border-champagne bg-wine-sunken p-4"><h4 className={`mb-2 ${label}`}>Studio Reply</h4><p className="whitespace-pre-wrap break-words text-body">{request.staffReply}</p></div>}<details className="my-4 border-t border-hairline pt-2"><summary className="flex min-h-11 cursor-pointer items-center font-ui text-small font-semibold text-champagne">Your Submitted Brief</summary><p className="whitespace-pre-wrap break-words text-body">{request.notes}</p><pre className="mt-3 whitespace-pre-wrap break-words font-sans text-small text-taupe">{request.sample}</pre></details>{request.status === "requested" && (confirm ? <div className="space-y-3"><p className="text-cream">Withdraw this pending request?</p><div className="flex flex-wrap items-center gap-4"><Button size="sm" disabled={busy} onClick={() => void withdraw()}>Confirm Withdrawal</Button><Button variant="link" size="link" onClick={() => setConfirm(false)}>Keep Request</Button></div></div> : <Button variant="link" size="link" onClick={() => setConfirm(true)}>Withdraw Request</Button>)}{error && <p role="alert" className={alertText}>{error}</p>}</article>;
}
function StaffReply({ request }: { request: FunctionReturnType<typeof api.academy.inbox>[number] }) {
  const reply = useMutation(api.academy.reply); const [busy,setBusy] = useState(false); const [notice,setNotice] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const raw = data.get("status"); const status = raw === "scheduled" || raw === "completed" || raw === "canceled" ? raw : "requested"; setBusy(true); setNotice(""); try { await reply({id:request._id, reply:String(data.get("reply")),status,scheduledAt:data.get("date") ? new Date(String(data.get("date"))+"Z").getTime() : undefined}); setNotice("Reply saved to the member’s account. No email sent."); } catch(err) {setNotice(message(err));} finally {setBusy(false);} }
  return <details className={`${card} text-body`}><summary className="flex min-h-11 cursor-pointer items-center font-ui text-small font-semibold text-cream">{request.name} · {request.serviceTitle} · {request.status}</summary><p className="my-3 break-all">{request.email}</p><p>{request.projectTitle} · {request.genre} · {request.wordCount} words</p><p>Timeline: {request.timeline}</p><p className="my-3 whitespace-pre-wrap break-words">{request.notes}</p><pre className="whitespace-pre-wrap break-words font-sans text-small text-taupe">{request.sample}</pre><form className="mt-4 grid gap-4" onSubmit={submit}><label className={fieldLabel}>Reply<Textarea name="reply" defaultValue={request.staffReply} minLength={2} maxLength={5000} required /></label><label className={fieldLabel}>Status<select name="status" className={nativeSelect} defaultValue={request.status}>{["requested","scheduled","completed","canceled"].map(s=><option key={s}>{s}</option>)}</select></label><label className={fieldLabel}>Appointment Time (UTC, Required for Scheduled)<Input name="date" type="datetime-local" /></label><Button type="submit" className="justify-self-start" disabled={busy}>Save Reply</Button>{notice && <p role="status" className={statusText}>{notice}</p>}</form></details>;
}
function StaffInbox() { const rows=useQuery(api.academy.inbox,{}); const interests=useQuery(api.academy.interestInbox,{}); return <section className="mt-16 border-t border-hairline pt-12"><p className={tagline}>Staff</p><h2 className={`mb-4 ${heading2}`}>Studio Inbox</h2><p className={`mb-6 ${muted}`}>Latest 100 requests. Replies appear in the member’s account; email delivery is not connected.</p><div className="grid gap-4">{rows ? rows.length ? rows.map(r=><StaffReply key={r._id} request={r}/>) : <p className={statusText}>No requests yet.</p> : <p role="status" className={statusText}>Loading inbox…</p>}</div><h3 className={`mt-10 mb-3 ${heading3}`}>Course Interest</h3><p className={`mb-4 ${muted}`}>Latest 100 active interests. Contact permission is limited to the selected class or future studio classes.</p>{interests ? interests.length ? <ul className="grid gap-3">{interests.map(i=><li key={i._id} className={`${card} text-body`}><p className="break-all text-cream">{i.email}</p><p>{i.courseTitle}</p><p className={muted}>Consent recorded {new Date(i.consentedAt).toISOString().slice(0,10)}</p></li>)}</ul> : <p className={statusText}>No active course interests.</p> : <p role="status" className={statusText}>Loading interests…</p>}</section>; }
function LiveStudio() {
  const catalog = useQuery(api.academy.catalog,{}); const {isAuthenticated} = useConvexAuth();
  const mine = useQuery(api.academy.mine,isAuthenticated ? {} : "skip");
  if (!catalog) return <p role="status" className={statusText}>Loading the studio…</p>;
  return <>
    <div className="mb-10 max-w-lg"><p className={tagline}>Work With Nia</p><h2 className={heading2}>Studio Services</h2></div><div className="grid items-start gap-6 lg:grid-cols-2">{catalog.services.length ? catalog.services.map(s=><ServiceCard key={s._id} service={s} authenticated={isAuthenticated} mine={mine}/>) : <p className={`${card} text-body`}>No services are accepting requests at the moment.</p>}</div>
    <section className={`${cardVariants({ variant: "raised" })} mt-16 p-6 sm:p-10`}><p className={tagline}>Learn</p><h2 className={heading2}>Courses, Workshops &amp; Masterclasses</h2><p className={`my-5 ${lead}`}>{catalog.courses.length ? "Explore the studio’s published learning opportunities." : "No courses are announced yet. Save your interest for future writing classes."}</p><div className="grid gap-4">{catalog.courses.map(c=><article key={c._id} className={`${card} text-body`}><h3 className={heading3}>{c.title}</h3><p className="my-3">{c.description}</p><p className={label}>{c.instructor} · {c.format.replaceAll("_"," ")} · {c.level}</p><p className="my-2">{c.workload} · {price(c.priceInCents)}</p>{c.startsAt && <p>{new Date(c.startsAt).toISOString().replace("T"," ").slice(0,16)} UTC</p>}<ul className="my-4 list-disc space-y-1 pl-5 marker:text-champagne">{c.outcomes.map(o=><li key={o}>{o}</li>)}</ul>{c.status === "closed" ? <Badge variant="outline">Registration Closed</Badge> : c.status === "open" && safeUrl(c.enrollmentUrl) ? <a className={button} href={safeUrl(c.enrollmentUrl)!} target="_blank" rel="noopener noreferrer">View Enrollment Details ↗</a> : <><p className={`mb-3 ${label}`}>Coming Soon · Not an Enrollment</p>{isAuthenticated && mine ? <InterestButton courseId={c._id} active={mine.interests.some(i=>i.courseId===c._id && i.active)}/> : <Link href="/signin?next=/academy" className={button}>Sign In to Save Interest</Link>}</>}</article>)}</div><div className="mt-10 border-t border-hairline pt-8"><h3 className={`mb-3 ${heading3}`}>Future Studio Classes</h3><p className={`mb-5 max-w-[65ch] ${muted}`}>Saving interest allows the studio to contact your account email about future classes. It does not enroll you, charge you, or add you to the general newsletter. Automated emails are not active yet.</p>{isAuthenticated && mine ? <InterestButton active={mine.interests.some(i=>!i.courseId && i.active)}/> : <Link href="/signin?next=/academy" className={button}>Sign In to Save Interest</Link>}</div></section>
    {mine && <section id="studio-requests" className="mt-16 scroll-mt-28"><p className={tagline}>Your Account</p><h2 className={heading2}>My Studio Requests</h2><p className={`my-5 ${lead}`}>Requests and staff replies are saved here. Check back for a response; no confirmation email is sent.</p><div className="grid gap-4">{mine.requests.length ? mine.requests.map(r=><RequestCard key={r._id} request={r}/>) : <p className={statusText}>You haven’t submitted a studio request yet.</p>}</div></section>}
    {mine?.canManage && <StaffInbox/>}
  </>;
}
export function AcademyStudio() { return authIsConfigured ? <QueryBoundary fallback={(_error,retry)=><StatePanel role="alert" eyebrow="Something went wrong" title="The Studio Is Temporarily Unavailable" actions={<Button type="button" onClick={retry}>Try Again</Button>}>We couldn’t load the studio’s services and courses.</StatePanel>}><LiveStudio/></QueryBoundary> : <StatePanel role="status" eyebrow="Not connected" title="The Studio Is Not Connected Yet">The studio is not connected yet. Please check back soon.</StatePanel>; }
