"use client";
import {useState} from "react";
import Link from "next/link";
import {useQuery} from "convex/react";
import {api} from "@/convex/_generated/api";
import {MembershipAction,ManageMembership} from "@/components/membership-action";
import {QueryBoundary} from "@/components/catalog/query-boundary";
import {authIsConfigured} from "@/lib/auth-client";
const currency = new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
function Plans(){const plans=useQuery(api.billing.plans,{});const [annual,setAnnual]=useState(false);return <><div className="my-8 flex gap-3">{[false,true].map(value=><button key={String(value)} aria-pressed={annual===value} onClick={()=>setAnnual(value)} className="min-h-11 rounded-full bg-white px-5">{value?"Annual":"Monthly"}</button>)}</div>{!plans?<p role="status">Loading membership plans…</p>:!plans.length?<p>No membership plans are currently available.</p>:<div className="grid gap-5 md:grid-cols-2">{plans.map(p=><article key={p._id} className="rounded-3xl bg-[var(--color-brand-surface)] p-8"><h2 className="text-2xl font-bold">{p.name}</h2><p className="my-4 text-3xl">{p.key==="free"?"Free":currency.format((annual?p.annualPriceInCents:p.monthlyPriceInCents)/100)}{p.key!=="free" && <span className="text-base"> / {annual?"year":"month"}</span>}</p><p>{p.description}</p><ul className="my-6 list-disc space-y-2 pl-5">{p.features.map(f=><li key={f}>{f}</li>)}</ul><MembershipAction name={p.name} tier={p.key==="free"?null:p.key} annual={annual} className="inline-flex min-h-11 items-center rounded-full bg-[var(--color-deep-plum)] px-5 py-3 text-white">{p.key==="free"?"Free Account":"Choose Plan"}</MembershipAction></article>)}</div>}<ManageMembership/></>;}
export default function MembershipPage(){return <main className="mx-auto max-w-6xl px-5 py-12 text-[var(--color-deep-plum)]"><h1 className="text-4xl font-bold">Join the Circle</h1><p className="mt-4">Explore the currently published membership plans.</p>{authIsConfigured?<QueryBoundary fallback={(_e,retry)=><p role="alert">Plans are unavailable. <button onClick={retry}>Retry</button></p>}><Plans/></QueryBoundary>:<p>Membership is not connected yet.</p>}<Link href="/contact" className="mt-8 inline-flex min-h-11 items-center underline">Questions? Contact the Circle ↗</Link></main>;}
